### ISSUE TITLE
How to rediret to the login page when the jwt token expired?

### ISSUE THREAD

**Issue by jianjunchang** [spring-cloud-samples/sample-gateway-oauth2login#11]
Hi, your sample project is very helpful to me when i am learning the spring cloud gateway with my custom oauth2 authorization server(which is also called uaa, the difference is that my uaa has a smaller accessTokenValiditySeconds config to the client, eg: 60s), but i have encountered a problem, when i'm accessing my resource server through the gateway router, the first time i will be redirect to the uaa's login page, it works very well, but when the jwt is expired, the resource server just show a 401 error page, i think the right behavior should be redirected to the login page again, so what wrong with me? how can i fix this? and if the resource server is a restful api server, i think the 401 response will be well, how can i config a web site resource server and a restful api resource server separately? the problem confuse me several days, hope your help, thanks very very much!

**Comment by jianjunchang** [comment]
I have also ask this [question](https://stackoverflow.com/questions/58352385/the-gateway-response-401-rather-than-redirect-to-login-page) in the stackoverflow, but have no body help me yet.

**Comment by spencergibb** [comment]
Support for refresh is in the future

**Comment by jianjunchang** [comment]
> Support for refresh is in the future

Thanks for your reply
